# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/digtwin',
                'doc_host': 'https://mldurga.github.io',
                'git_url': 'https://github.com/mldurga/digtwin',
                'lib_path': 'digtwin'},
  'syms': {'digtwin.core': {'digtwin.core.foo': ('core.html#foo', 'digtwin/core.py')}}}
